name: fixo_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.0.5

  # For making HTTP requests
  http: ^1.1.0

  # Socket.IO client for real-time chat
  socket_io_client: ^2.0.0

  # Local storage for login/session persistence
  shared_preferences: ^2.2.3
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  firebase_storage: ^13.0.2
  
  # Image and file handling
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  
  # URL launcher for phone calls and links
  url_launcher: ^6.2.1
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
